const express = require('express');
const cors = require('cors');

const app = express();

app.use(cors({
  origin: ['https://cs-poc-pr0n8qqumo0fl7jqn1n8qhk.web.app', 'http://localhost:3000'],
  methods: ['POST', 'OPTIONS'],
  allowedHeaders: ['Content-Type'],
  credentials: true,
}));

app.use(express.json());

app.options('/api/generate-strategic-insights', cors()); // explicit preflight handling

app.post('/api/generate-strategic-insights', async (req, res) => {
  const { componentName, userPrompt } = req.body;

  // TODO: Explicitly integrate GPT-4o or Gemini AI logic here
  const aiGeneratedCode = {
    jsx: "<div>Your generated React JSX explicitly here</div>",
    css: "/* Your generated CSS explicitly here */",
    insights: "Your strategic insights explicitly generated by AI"
  };

  res.status(200).json({
    success: true,
    ...aiGeneratedCode
  });
});

app.get('/', (req, res) => {
  res.status(200).send('Root endpoint OK');
});

module.exports = app;
